/*
 * Intel OpenCL C IVF benchmark.
 *
 * This path exists because the local Intel OpenCL driver crashes when SYCL
 * SPIR-V generated by plain -O2 is JIT-compiled for the RaptorLake-S iGPU.
 * OpenCL C source kernels compile through the same Intel OpenCL runtime without
 * disabling device optimizations.
 */
#include "pthread_common.h"

#include <CL/cl.h>

#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <limits>
#include <queue>
#include <sstream>
#include <string>
#include <vector>

using namespace pthread_ann;

namespace {

const size_t kRecallAt = 100;

const char* kIvfTop4Kernel = R"CLC(
__kernel void ivf_block_top4(__global const float* base,
                             __global const uint* flat_ids,
                             __global const uint* list_offsets,
                             __global const int* probe_ids,
                             __global const float* query,
                             __global float* partial_dist,
                             __global uint* partial_id,
                             const int nprobe,
                             const int probe_stride,
                             const int query_stride,
                             const int work_items_per_query,
                             const int dim) {
    const int qi = (int)get_global_id(0);
    const int lane = (int)get_global_id(1);

    float d0 = FLT_MAX;
    float d1 = FLT_MAX;
    float d2 = FLT_MAX;
    float d3 = FLT_MAX;
    uint i0 = 0;
    uint i1 = 0;
    uint i2 = 0;
    uint i3 = 0;

    for (int pi = 0; pi < nprobe; ++pi) {
        const int cid = probe_ids[qi * probe_stride + pi];
        const uint begin = list_offsets[cid];
        const uint end = list_offsets[cid + 1];
        for (uint pos = (uint)lane; pos < end - begin; pos += (uint)work_items_per_query) {
            const uint vid = flat_ids[begin + pos];
            __global const float* b = base + (ulong)vid * (ulong)dim;
            float dot = 0.0f;
            for (int d = 0; d < dim; ++d) {
                dot += b[d] * query[d * query_stride + qi];
            }
            const float dist = 1.0f - dot;
            if (dist < d0) {
                d3 = d2; i3 = i2;
                d2 = d1; i2 = i1;
                d1 = d0; i1 = i0;
                d0 = dist; i0 = vid;
            } else if (dist < d1) {
                d3 = d2; i3 = i2;
                d2 = d1; i2 = i1;
                d1 = dist; i1 = vid;
            } else if (dist < d2) {
                d3 = d2; i3 = i2;
                d2 = dist; i2 = vid;
            } else if (dist < d3) {
                d3 = dist; i3 = vid;
            }
        }
    }

    const int out_base = (qi * work_items_per_query + lane) * 4;
    partial_dist[out_base] = d0;
    partial_id[out_base] = i0;
    partial_dist[out_base + 1] = d1;
    partial_id[out_base + 1] = i1;
    partial_dist[out_base + 2] = d2;
    partial_id[out_base + 2] = i2;
    partial_dist[out_base + 3] = d3;
    partial_id[out_base + 3] = i3;
}
)CLC";

struct Config {
    std::string data_dir;
    std::string device;
    std::string method;
    std::string notes;
    std::string csv_path;
    std::string best_csv_path;
    std::string nprobe_list_arg;
    size_t batch_size;
    int nlist;
    int kmeans_iters;
    int workgroup_size;
    int local_k;
    size_t nq;
    double baseline_ms;
    double target_recall;
    Config()
        : data_dir("../anndata"),
          device("intel-gpu"),
          method("IntelOpenCLGPU-OpenCLC"),
          notes(""),
          csv_path("files/results/pthread_opencl_gpu_results.csv"),
          best_csv_path("files/results/pthread_opencl_gpu_best.csv"),
          nprobe_list_arg("76,78,80,82,84"),
          batch_size(1000),
          nlist(2048),
          kmeans_iters(12),
          workgroup_size(128),
          local_k(4),
          nq(1000),
          baseline_ms(0.0),
          target_recall(0.95) {}
};

Config parse_args(int argc, char** argv) {
    Config cfg;
    for (int i = 1; i < argc; ++i) {
        std::string a(argv[i]);
        if (a == "--data" && i + 1 < argc) cfg.data_dir = argv[++i];
        else if (a == "--device" && i + 1 < argc) cfg.device = argv[++i];
        else if (a == "--method" && i + 1 < argc) cfg.method = argv[++i];
        else if (a == "--notes" && i + 1 < argc) cfg.notes = argv[++i];
        else if (a == "--csv" && i + 1 < argc) cfg.csv_path = argv[++i];
        else if (a == "--best-csv" && i + 1 < argc) cfg.best_csv_path = argv[++i];
        else if (a == "--nprobe-list" && i + 1 < argc) cfg.nprobe_list_arg = argv[++i];
        else if (a == "--batch" && i + 1 < argc) cfg.batch_size = static_cast<size_t>(std::atoi(argv[++i]));
        else if (a == "--nlist" && i + 1 < argc) cfg.nlist = std::atoi(argv[++i]);
        else if (a == "--iters" && i + 1 < argc) cfg.kmeans_iters = std::atoi(argv[++i]);
        else if (a == "--workgroup-size" && i + 1 < argc) cfg.workgroup_size = std::atoi(argv[++i]);
        else if (a == "--local-k" && i + 1 < argc) cfg.local_k = std::atoi(argv[++i]);
        else if (a == "--nq" && i + 1 < argc) cfg.nq = static_cast<size_t>(std::atoi(argv[++i]));
        else if (a == "--baseline-ms" && i + 1 < argc) cfg.baseline_ms = std::atof(argv[++i]);
        else if (a == "--target-recall" && i + 1 < argc) cfg.target_recall = std::atof(argv[++i]);
        else if ((a == "--algo" || a == "--query-block") && i + 1 < argc) ++i;
    }
    if (cfg.batch_size == 0) cfg.batch_size = 1;
    if (cfg.nlist <= 0) cfg.nlist = 2048;
    if (cfg.kmeans_iters <= 0) cfg.kmeans_iters = 12;
    if (cfg.workgroup_size != 64 && cfg.workgroup_size != 128 && cfg.workgroup_size != 256) {
        cfg.workgroup_size = 128;
    }
    if (cfg.local_k != 4) cfg.local_k = 4;
    if (cfg.target_recall <= 0.0 || cfg.target_recall > 1.0) cfg.target_recall = 0.95;
    return cfg;
}

std::string csv_quote(const std::string& s) {
    std::string out = "\"";
    for (size_t i = 0; i < s.size(); ++i) {
        if (s[i] == '"') out += "\"\"";
        else out += s[i];
    }
    out += "\"";
    return out;
}

bool needs_header(const std::string& path) {
    std::ifstream in(path.c_str(), std::ios::binary);
    if (!in.good()) return true;
    in.seekg(0, std::ios::end);
    return in.tellg() == std::streampos(0);
}

std::vector<int> parse_int_list(const std::string& text) {
    std::vector<int> values;
    std::stringstream ss(text);
    std::string item;
    while (std::getline(ss, item, ',')) {
        int v = std::atoi(item.c_str());
        if (v > 0) values.push_back(v);
    }
    if (values.empty()) values.push_back(80);
    std::sort(values.begin(), values.end());
    values.erase(std::unique(values.begin(), values.end()), values.end());
    return values;
}

void push_topk(std::priority_queue<std::pair<float, uint32_t> >& heap,
               float distance,
               uint32_t id,
               size_t k) {
    if (heap.size() < k) {
        heap.push(std::make_pair(distance, id));
    } else if (distance < heap.top().first) {
        heap.push(std::make_pair(distance, id));
        heap.pop();
    }
}

double recall_at_k(std::priority_queue<std::pair<float, uint32_t> > heap,
                   const int* gt,
                   size_t gt_d,
                   size_t qid,
                   size_t k) {
    std::vector<uint32_t> truth(k);
    for (size_t i = 0; i < k; ++i) truth[i] = static_cast<uint32_t>(gt[qid * gt_d + i]);
    std::sort(truth.begin(), truth.end());

    size_t hit = 0;
    while (!heap.empty()) {
        if (std::binary_search(truth.begin(), truth.end(), heap.top().second)) ++hit;
        heap.pop();
    }
    return static_cast<double>(hit) / static_cast<double>(k);
}

struct SimpleIVFIndex {
    size_t n;
    size_t d;
    int nlist;
    std::vector<float> centroids;
    std::vector<std::vector<uint32_t> > lists;
};

void build_simple_ivf_index(const float* base,
                            size_t n,
                            size_t d,
                            int nlist,
                            int kmeans_iters,
                            SimpleIVFIndex& idx) {
    idx.n = n;
    idx.d = d;
    idx.nlist = std::min<int>(nlist, static_cast<int>(n));
    idx.centroids.assign(static_cast<size_t>(idx.nlist) * d, 0.0f);
    idx.lists.assign(idx.nlist, std::vector<uint32_t>());

    for (int c = 0; c < idx.nlist; ++c) {
        size_t si = static_cast<size_t>(c) * n / idx.nlist;
        std::copy(base + si * d, base + (si + 1) * d,
                  idx.centroids.begin() + static_cast<size_t>(c) * d);
    }

    std::vector<int> assign(n, 0);
    std::vector<int> counts(idx.nlist, 0);
    std::vector<double> sums(static_cast<size_t>(idx.nlist) * d, 0.0);
    for (int iter = 0; iter < kmeans_iters; ++iter) {
        std::fill(counts.begin(), counts.end(), 0);
        std::fill(sums.begin(), sums.end(), 0.0);
        for (size_t i = 0; i < n; ++i) {
            const float* x = base + i * d;
            int best = 0;
            float best_dist = std::numeric_limits<float>::max();
            for (int c = 0; c < idx.nlist; ++c) {
                const float* ct = &idx.centroids[static_cast<size_t>(c) * d];
                float dist = 0.0f;
                for (size_t j = 0; j < d; ++j) {
                    float diff = x[j] - ct[j];
                    dist += diff * diff;
                }
                if (dist < best_dist) {
                    best_dist = dist;
                    best = c;
                }
            }
            assign[i] = best;
            counts[best]++;
            double* sum = &sums[static_cast<size_t>(best) * d];
            for (size_t j = 0; j < d; ++j) sum[j] += x[j];
        }

        for (int c = 0; c < idx.nlist; ++c) {
            if (counts[c] == 0) continue;
            double inv = 1.0 / static_cast<double>(counts[c]);
            for (size_t j = 0; j < d; ++j) {
                idx.centroids[static_cast<size_t>(c) * d + j] =
                    static_cast<float>(sums[static_cast<size_t>(c) * d + j] * inv);
            }
        }
    }

    for (int c = 0; c < idx.nlist; ++c) idx.lists[c].clear();
    for (size_t i = 0; i < n; ++i) idx.lists[assign[i]].push_back(static_cast<uint32_t>(i));
}

void select_probe_ids(const SimpleIVFIndex& idx,
                      const float* query,
                      int nprobe,
                      std::vector<int>& probe_ids) {
    int np = std::min(nprobe, idx.nlist);
    std::vector<std::pair<float, int> > coarse(idx.nlist);
    for (int c = 0; c < idx.nlist; ++c) {
        const float* ct = &idx.centroids[static_cast<size_t>(c) * idx.d];
        float dot = 0.0f;
        for (size_t j = 0; j < idx.d; ++j) dot += ct[j] * query[j];
        coarse[c] = std::make_pair(1.0f - dot, c);
    }
    if (np < idx.nlist) {
        std::nth_element(coarse.begin(), coarse.begin() + np, coarse.end());
    } else {
        std::sort(coarse.begin(), coarse.end());
    }
    probe_ids.resize(np);
    for (int i = 0; i < np; ++i) probe_ids[i] = coarse[i].second;
}

size_t max_candidates_for_nprobe(const SimpleIVFIndex& idx, int nprobe) {
    std::vector<size_t> sizes;
    sizes.reserve(idx.lists.size());
    for (size_t i = 0; i < idx.lists.size(); ++i) sizes.push_back(idx.lists[i].size());
    std::sort(sizes.begin(), sizes.end(), std::greater<size_t>());
    size_t limit = std::min<size_t>(static_cast<size_t>(std::min(nprobe, idx.nlist)), sizes.size());
    size_t total = 0;
    for (size_t i = 0; i < limit; ++i) total += sizes[i];
    return std::max<size_t>(total, kRecallAt);
}

std::priority_queue<std::pair<float, uint32_t> >
select_topk_from_candidates(const float* dist,
                            const uint32_t* ids,
                            size_t count,
                            size_t k) {
    std::priority_queue<std::pair<float, uint32_t> > heap;
    for (size_t i = 0; i < count; ++i) {
        push_topk(heap, dist[i], ids[i], k);
    }
    return heap;
}

bool cl_ok(cl_int err, const char* what) {
    if (err == CL_SUCCESS) return true;
    std::cerr << "OpenCL error at " << what << ": " << err << "\n";
    return false;
}

std::string get_platform_name(cl_platform_id platform) {
    size_t size = 0;
    clGetPlatformInfo(platform, CL_PLATFORM_NAME, 0, nullptr, &size);
    std::string name(size, '\0');
    if (size > 0) clGetPlatformInfo(platform, CL_PLATFORM_NAME, size, &name[0], nullptr);
    if (!name.empty() && name.back() == '\0') name.pop_back();
    return name;
}

std::string get_device_string(cl_device_id device, cl_device_info info) {
    size_t size = 0;
    clGetDeviceInfo(device, info, 0, nullptr, &size);
    std::string value(size, '\0');
    if (size > 0) clGetDeviceInfo(device, info, size, &value[0], nullptr);
    if (!value.empty() && value.back() == '\0') value.pop_back();
    return value;
}

bool select_intel_graphics_device(cl_platform_id& platform_out,
                                  cl_device_id& device_out,
                                  std::string& platform_name,
                                  std::string& device_name,
                                  std::string& driver_version) {
    cl_uint platform_count = 0;
    cl_int err = clGetPlatformIDs(0, nullptr, &platform_count);
    if (!cl_ok(err, "clGetPlatformIDs(count)") || platform_count == 0) return false;

    std::vector<cl_platform_id> platforms(platform_count);
    err = clGetPlatformIDs(platform_count, platforms.data(), nullptr);
    if (!cl_ok(err, "clGetPlatformIDs(list)") ) return false;

    for (size_t pi = 0; pi < platforms.size(); ++pi) {
        std::string name = get_platform_name(platforms[pi]);
        if (name.find("Intel") == std::string::npos ||
            name.find("Graphics") == std::string::npos) {
            continue;
        }
        cl_uint device_count = 0;
        err = clGetDeviceIDs(platforms[pi], CL_DEVICE_TYPE_GPU, 0, nullptr, &device_count);
        if (err != CL_SUCCESS || device_count == 0) continue;
        std::vector<cl_device_id> devices(device_count);
        err = clGetDeviceIDs(platforms[pi], CL_DEVICE_TYPE_GPU, device_count, devices.data(), nullptr);
        if (err != CL_SUCCESS) continue;
        platform_out = platforms[pi];
        device_out = devices[0];
        platform_name = name;
        device_name = get_device_string(device_out, CL_DEVICE_NAME);
        driver_version = get_device_string(device_out, CL_DRIVER_VERSION);
        return true;
    }
    return false;
}

cl_program build_opencl_program(cl_context context,
                                cl_device_id device,
                                const char* source,
                                const char* options) {
    cl_int err = CL_SUCCESS;
    size_t source_len = std::char_traits<char>::length(source);
    cl_program program = clCreateProgramWithSource(context, 1, &source, &source_len, &err);
    if (!cl_ok(err, "clCreateProgramWithSource")) return nullptr;
    err = clBuildProgram(program, 1, &device, options, nullptr, nullptr);
    if (err != CL_SUCCESS) {
        size_t log_size = 0;
        clGetProgramBuildInfo(program, device, CL_PROGRAM_BUILD_LOG, 0, nullptr, &log_size);
        std::string log(log_size, '\0');
        if (log_size > 0) {
            clGetProgramBuildInfo(program, device, CL_PROGRAM_BUILD_LOG, log_size, &log[0], nullptr);
        }
        if (!log.empty() && log.back() == '\0') log.pop_back();
        std::cerr << "OpenCL build failed: " << err << "\n" << log << "\n";
        clReleaseProgram(program);
        return nullptr;
    }
    return program;
}

} // namespace

int main(int argc, char** argv) {
    Config cfg = parse_args(argc, argv);
    ensure_dir("files");
    ensure_dir("files/results");

    size_t base_n = 0, base_d = 0, query_n = 0, query_d = 0, gt_n = 0, gt_d = 0;
    float* base = load_data<float>(join_path(cfg.data_dir, "DEEP100K.base.100k.fbin"), base_n, base_d);
    float* query = load_data<float>(join_path(cfg.data_dir, "DEEP100K.query.fbin"), query_n, query_d);
    int* gt = load_data<int>(join_path(cfg.data_dir, "DEEP100K.gt.query.100k.top100.bin"), gt_n, gt_d);
    if (base_d != query_d || gt_d < kRecallAt) {
        std::cerr << "FATAL: incompatible data dimensions\n";
        return 2;
    }
    if (base_n > static_cast<size_t>(std::numeric_limits<int>::max()) ||
        base_d > static_cast<size_t>(std::numeric_limits<int>::max()) ||
        cfg.batch_size > static_cast<size_t>(std::numeric_limits<int>::max())) {
        std::cerr << "FATAL: OpenCL IVF path expects int-sized dimensions\n";
        return 2;
    }

    cl_platform_id platform = nullptr;
    cl_device_id device = nullptr;
    std::string platform_name;
    std::string device_name;
    std::string driver_version;
    if (!select_intel_graphics_device(platform, device, platform_name, device_name, driver_version)) {
        std::cerr << "FATAL: Intel OpenCL Graphics GPU not found\n";
        return 3;
    }

    cl_int err = CL_SUCCESS;
    cl_context context = clCreateContext(nullptr, 1, &device, nullptr, nullptr, &err);
    if (!cl_ok(err, "clCreateContext")) return 3;
    cl_command_queue queue = clCreateCommandQueueWithProperties(context, device, nullptr, &err);
    if (!cl_ok(err, "clCreateCommandQueueWithProperties")) return 3;
    long long cl_build_t0 = now_us();
    cl_program program = build_opencl_program(context, device, kIvfTop4Kernel, "-cl-std=CL2.0");
    double cl_build_sec = static_cast<double>(now_us() - cl_build_t0) / 1000000.0;
    if (!program) return 4;
    cl_kernel kernel = clCreateKernel(program, "ivf_block_top4", &err);
    if (!cl_ok(err, "clCreateKernel")) return 4;

    size_t nq = std::min(cfg.nq, std::min(query_n, gt_n));
    long long build_t0 = now_us();
    SimpleIVFIndex ivf;
    build_simple_ivf_index(base, base_n, base_d, cfg.nlist, cfg.kmeans_iters, ivf);
    double build_sec = static_cast<double>(now_us() - build_t0) / 1000000.0;

    std::vector<uint32_t> list_offsets(static_cast<size_t>(ivf.nlist) + 1, 0);
    for (int c = 0; c < ivf.nlist; ++c) {
        list_offsets[static_cast<size_t>(c) + 1] =
            list_offsets[static_cast<size_t>(c)] +
            static_cast<uint32_t>(ivf.lists[c].size());
    }
    std::vector<uint32_t> flat_ids(list_offsets.back());
    for (int c = 0; c < ivf.nlist; ++c) {
        std::copy(ivf.lists[c].begin(), ivf.lists[c].end(),
                  flat_ids.begin() + list_offsets[static_cast<size_t>(c)]);
    }

    std::vector<int> nprobe_values = parse_int_list(cfg.nprobe_list_arg);
    for (size_t i = 0; i < nprobe_values.size(); ++i) {
        nprobe_values[i] = std::min(nprobe_values[i], ivf.nlist);
    }
    nprobe_values.erase(std::unique(nprobe_values.begin(), nprobe_values.end()),
                        nprobe_values.end());
    int max_nprobe = nprobe_values.empty() ? std::min(80, ivf.nlist)
                                           : nprobe_values.back();

    const size_t batch_size = std::min(cfg.batch_size, nq);
    const size_t base_total = base_n * base_d;
    const size_t query_batch_total = batch_size * base_d;
    const size_t max_candidate_capacity = max_candidates_for_nprobe(ivf, max_nprobe);
    const size_t partial_capacity = static_cast<size_t>(cfg.workgroup_size) *
                                    static_cast<size_t>(cfg.local_k);
    const size_t partial_total = batch_size * partial_capacity;

    std::vector<float> query_batch(query_batch_total);
    std::vector<float> dist_host(partial_total);
    std::vector<uint32_t> id_host(partial_total);
    std::vector<int> batch_probe_ids(batch_size * static_cast<size_t>(max_nprobe));
    std::vector<int> probe_ids;

    cl_mem base_dev = clCreateBuffer(context, CL_MEM_READ_ONLY | CL_MEM_COPY_HOST_PTR,
                                     base_total * sizeof(float), base, &err);
    if (!cl_ok(err, "base buffer")) return 5;
    cl_mem query_dev = clCreateBuffer(context, CL_MEM_READ_ONLY,
                                      query_batch_total * sizeof(float), nullptr, &err);
    if (!cl_ok(err, "query buffer")) return 5;
    cl_mem flat_ids_dev = clCreateBuffer(context, CL_MEM_READ_ONLY | CL_MEM_COPY_HOST_PTR,
                                         flat_ids.size() * sizeof(uint32_t), flat_ids.data(), &err);
    if (!cl_ok(err, "flat id buffer")) return 5;
    cl_mem offsets_dev = clCreateBuffer(context, CL_MEM_READ_ONLY | CL_MEM_COPY_HOST_PTR,
                                        list_offsets.size() * sizeof(uint32_t), list_offsets.data(), &err);
    if (!cl_ok(err, "offset buffer")) return 5;
    cl_mem probe_dev = clCreateBuffer(context, CL_MEM_READ_ONLY,
                                      batch_probe_ids.size() * sizeof(int), nullptr, &err);
    if (!cl_ok(err, "probe buffer")) return 5;
    cl_mem dist_dev = clCreateBuffer(context, CL_MEM_WRITE_ONLY,
                                     partial_total * sizeof(float), nullptr, &err);
    if (!cl_ok(err, "dist buffer")) return 5;
    cl_mem id_dev = clCreateBuffer(context, CL_MEM_WRITE_ONLY,
                                   partial_total * sizeof(uint32_t), nullptr, &err);
    if (!cl_ok(err, "id buffer")) return 5;

    {
        size_t warm_bs = std::min(batch_size, nq);
        for (size_t local_q = 0; local_q < warm_bs; ++local_q) {
            const float* qptr = query + local_q * base_d;
            for (size_t d = 0; d < base_d; ++d) query_batch[d * batch_size + local_q] = qptr[d];
            select_probe_ids(ivf, qptr, max_nprobe, probe_ids);
            std::copy(probe_ids.begin(), probe_ids.end(),
                      batch_probe_ids.begin() + local_q * static_cast<size_t>(max_nprobe));
        }
        clEnqueueWriteBuffer(queue, query_dev, CL_TRUE, 0,
                             query_batch_total * sizeof(float), query_batch.data(), 0, nullptr, nullptr);
        clEnqueueWriteBuffer(queue, probe_dev, CL_TRUE, 0,
                             warm_bs * static_cast<size_t>(max_nprobe) * sizeof(int),
                             batch_probe_ids.data(), 0, nullptr, nullptr);
        int nprobe_arg = max_nprobe;
        int probe_stride = max_nprobe;
        int query_stride = static_cast<int>(batch_size);
        int work_items = cfg.workgroup_size;
        int dim = static_cast<int>(base_d);
        int ai = 0;
        clSetKernelArg(kernel, ai++, sizeof(cl_mem), &base_dev);
        clSetKernelArg(kernel, ai++, sizeof(cl_mem), &flat_ids_dev);
        clSetKernelArg(kernel, ai++, sizeof(cl_mem), &offsets_dev);
        clSetKernelArg(kernel, ai++, sizeof(cl_mem), &probe_dev);
        clSetKernelArg(kernel, ai++, sizeof(cl_mem), &query_dev);
        clSetKernelArg(kernel, ai++, sizeof(cl_mem), &dist_dev);
        clSetKernelArg(kernel, ai++, sizeof(cl_mem), &id_dev);
        clSetKernelArg(kernel, ai++, sizeof(int), &nprobe_arg);
        clSetKernelArg(kernel, ai++, sizeof(int), &probe_stride);
        clSetKernelArg(kernel, ai++, sizeof(int), &query_stride);
        clSetKernelArg(kernel, ai++, sizeof(int), &work_items);
        clSetKernelArg(kernel, ai++, sizeof(int), &dim);
        size_t global[2] = {warm_bs, static_cast<size_t>(cfg.workgroup_size)};
        clEnqueueNDRangeKernel(queue, kernel, 2, nullptr, global, nullptr, 0, nullptr, nullptr);
        clFinish(queue);
    }

    bool header = needs_header(cfg.csv_path);
    std::ofstream out(cfg.csv_path.c_str(), std::ios::app);
    if (header) {
        out << "experiment,method,nthreads,param1,param2,latency_ms,recall@100,speedup,"
            << "index_mb,build_sec,encode_us,lut_us,scan_us,select_us,rerank_us,notes\n";
    }

    bool best_valid = false;
    int best_nprobe = 0;
    double best_latency = std::numeric_limits<double>::max();
    double best_recall = 0.0;
    double best_speedup = 0.0;
    std::string best_method;
    std::string best_notes;

    for (size_t npi = 0; npi < nprobe_values.size(); ++npi) {
        int nprobe = nprobe_values[npi];
        double recall_sum = 0.0;
        double select_us_sum = 0.0;
        long long t0 = now_us();

        for (size_t batch_begin = 0; batch_begin < nq; batch_begin += batch_size) {
            size_t bs = std::min(batch_size, nq - batch_begin);
            for (size_t local_q = 0; local_q < bs; ++local_q) {
                size_t qi = batch_begin + local_q;
                const float* qptr = query + qi * base_d;
                for (size_t d = 0; d < base_d; ++d) {
                    query_batch[d * batch_size + local_q] = qptr[d];
                }
                select_probe_ids(ivf, qptr, nprobe, probe_ids);
                std::copy(probe_ids.begin(), probe_ids.end(),
                          batch_probe_ids.begin() + local_q * static_cast<size_t>(max_nprobe));
            }

            clEnqueueWriteBuffer(queue, query_dev, CL_TRUE, 0,
                                 query_batch_total * sizeof(float), query_batch.data(), 0, nullptr, nullptr);
            clEnqueueWriteBuffer(queue, probe_dev, CL_TRUE, 0,
                                 bs * static_cast<size_t>(max_nprobe) * sizeof(int),
                                 batch_probe_ids.data(), 0, nullptr, nullptr);

            int nprobe_arg = nprobe;
            int probe_stride = max_nprobe;
            int query_stride = static_cast<int>(batch_size);
            int work_items = cfg.workgroup_size;
            int dim = static_cast<int>(base_d);
            int ai = 0;
            clSetKernelArg(kernel, ai++, sizeof(cl_mem), &base_dev);
            clSetKernelArg(kernel, ai++, sizeof(cl_mem), &flat_ids_dev);
            clSetKernelArg(kernel, ai++, sizeof(cl_mem), &offsets_dev);
            clSetKernelArg(kernel, ai++, sizeof(cl_mem), &probe_dev);
            clSetKernelArg(kernel, ai++, sizeof(cl_mem), &query_dev);
            clSetKernelArg(kernel, ai++, sizeof(cl_mem), &dist_dev);
            clSetKernelArg(kernel, ai++, sizeof(cl_mem), &id_dev);
            clSetKernelArg(kernel, ai++, sizeof(int), &nprobe_arg);
            clSetKernelArg(kernel, ai++, sizeof(int), &probe_stride);
            clSetKernelArg(kernel, ai++, sizeof(int), &query_stride);
            clSetKernelArg(kernel, ai++, sizeof(int), &work_items);
            clSetKernelArg(kernel, ai++, sizeof(int), &dim);
            size_t global[2] = {bs, static_cast<size_t>(cfg.workgroup_size)};
            err = clEnqueueNDRangeKernel(queue, kernel, 2, nullptr, global, nullptr, 0, nullptr, nullptr);
            if (!cl_ok(err, "clEnqueueNDRangeKernel")) return 6;
            clEnqueueReadBuffer(queue, dist_dev, CL_TRUE, 0,
                                bs * partial_capacity * sizeof(float), dist_host.data(), 0, nullptr, nullptr);
            clEnqueueReadBuffer(queue, id_dev, CL_TRUE, 0,
                                bs * partial_capacity * sizeof(uint32_t), id_host.data(), 0, nullptr, nullptr);

            for (size_t local_q = 0; local_q < bs; ++local_q) {
                size_t qi = batch_begin + local_q;
                long long select_t0 = now_us();
                std::priority_queue<std::pair<float, uint32_t> > heap =
                    select_topk_from_candidates(dist_host.data() + local_q * partial_capacity,
                                                id_host.data() + local_q * partial_capacity,
                                                partial_capacity,
                                                kRecallAt);
                select_us_sum += static_cast<double>(now_us() - select_t0);
                recall_sum += recall_at_k(heap, gt, gt_d, qi, kRecallAt);
            }
        }

        double total_us = static_cast<double>(now_us() - t0);
        double latency_ms = total_us / 1000.0 / static_cast<double>(nq);
        double recall = recall_sum / static_cast<double>(nq);
        double select_us = select_us_sum / static_cast<double>(nq);
        double scan_us = latency_ms * 1000.0 - select_us;
        if (scan_us < 0.0) scan_us = 0.0;
        double speedup = cfg.baseline_ms > 0.0 ? cfg.baseline_ms / latency_ms : 0.0;

        std::string method = cfg.method + "-IVF-nl" + std::to_string(ivf.nlist);
        std::string notes = cfg.notes;
        if (!notes.empty()) notes += "; ";
        notes += "backend=opencl_c; platform=" + platform_name + "; device=" + device_name;
        notes += "; driver=" + driver_version + "; cl_build=-cl-std=CL2.0";
        notes += "; host_compile=O2; target_recall=" + std::to_string(cfg.target_recall);
        notes += "; batch=" + std::to_string(batch_size);
        notes += "; candidate_capacity=" + std::to_string(max_candidate_capacity);
        notes += "; gpu_block_top4=1; workgroup=" + std::to_string(cfg.workgroup_size);
        notes += "; local_k=4; partial_candidates=" + std::to_string(partial_capacity);
        notes += "; coarse_host=1; final_topk_host=1; cl_build_sec=" + std::to_string(cl_build_sec);

        out << "OpenCL-IVF," << method << ",0,nprobe," << nprobe
            << "," << latency_ms
            << "," << recall
            << "," << speedup
            << ",0," << build_sec
            << ",0,0," << scan_us
            << "," << select_us
            << ",0," << csv_quote(notes) << "\n";

        std::cout << "OpenCL IVF search: nq=" << nq
                  << " device=" << device_name
                  << " nlist=" << ivf.nlist
                  << " nprobe=" << nprobe
                  << " latency_ms=" << latency_ms
                  << " recall@100=" << recall
                  << " speedup=" << speedup << std::endl;

        if (recall >= cfg.target_recall && latency_ms < best_latency) {
            best_valid = true;
            best_nprobe = nprobe;
            best_latency = latency_ms;
            best_recall = recall;
            best_speedup = speedup;
            best_method = method;
            best_notes = notes;
        }
    }

    std::ofstream best_out(cfg.best_csv_path.c_str());
    best_out << "criterion,experiment,method,nthreads,param1,param2,latency_ms,recall@100,"
             << "speedup,index_mb,build_sec,notes\n";
    if (best_valid) {
        best_out << "min latency with recall@100>=" << cfg.target_recall
                 << ",OpenCL-IVF," << best_method << ",0,nprobe," << best_nprobe
                 << "," << best_latency
                 << "," << best_recall
                 << "," << best_speedup
                 << ",0," << build_sec
                 << "," << csv_quote(best_notes) << "\n";
        std::cout << "OpenCL IVF best: nprobe=" << best_nprobe
                  << " latency_ms=" << best_latency
                  << " recall@100=" << best_recall << std::endl;
    } else {
        best_out << "min latency with recall@100>=" << cfg.target_recall
                 << ",NONE,,,,,0,0,0,0," << build_sec
                 << ",\"no candidate satisfies recall constraint\"\n";
        std::cout << "OpenCL IVF best: no candidate satisfies recall@100 >= "
                  << cfg.target_recall << std::endl;
    }

    clReleaseMemObject(id_dev);
    clReleaseMemObject(dist_dev);
    clReleaseMemObject(probe_dev);
    clReleaseMemObject(offsets_dev);
    clReleaseMemObject(flat_ids_dev);
    clReleaseMemObject(query_dev);
    clReleaseMemObject(base_dev);
    clReleaseKernel(kernel);
    clReleaseProgram(program);
    clReleaseCommandQueue(queue);
    clReleaseContext(context);
    delete[] base;
    delete[] query;
    delete[] gt;
    return 0;
}
